sylius_mailer:
    sender:
      name: SyliusOnlineCourse admin
      address: kuba@test.com
    emails:
      app_supplier_trusted:
        subject: "You've been trusted!"
        template: "Supplier/Email/supplierTrusted.html.twig"
      